=encoding utf8

=head1 NAME

perldelta - what is new for perl v5.26.0

=head1 DESCRIPTION

As of the planned release date of 5.26.0 and 5.26.0c perldelta was not yet merged
with all 5.25.x documents.

Hence you need to check them all individually:

=over

=item L<perl5250delta>

=item L<perl5251delta>

=item L<perl5252delta>

=item L<perl5253delta>

=item L<perl5254delta>

=item L<perl5255delta>

=item L<perl5256delta>

=item L<perl5257delta>

=item L<perl5258delta>

=item L<perl5259delta>

=item L<perl52510delta>

=item L<perl52511delta>

=item L<perl52512delta>

=back

=cut
