=encoding utf8

=head1 NAME

perlcdelta - what is new for cperl v5.27.3

=head1 DESCRIPTION

This document describes differences between the cperl 5.27.2 and the cperl
5.27.3 release.

If you are upgrading from an earlier release such as v5.27.1c, first read
L<perl5272cdelta>, which describes differences between v5.27.1c and v5.27.2c.

=head1 Notice

XXX Any important notices here

=head1 Core Enhancements

XXX New core language features go here.  Summarize user-visible core language
enhancements.  Particularly prominent performance optimisations could go
here, but most should go in the L</Performance Enhancements> section.

[ List each enhancement as a =head2 entry ]

=head2 Computed shaped array sizes

This is now a valid shaped array delaration, with the lhs array size
computed from the number of constant elements in the rhs list
expressions. The array must only consist of compile-time scalars.

    my @a[] = (0,1,2);

C<my @a[];> without assignment is still a syntax error.

See L<[cperl #210]|https://github.com/perl11/cperl/issues/210>

=head1 Security

=head2 Disallow illegal glob with embedded NUL

E.g. C<< <$fh\000> >> throws now the safe syscalls warning, and errors
with C<Glob not terminated>, and does not pass the illegal glob path
to the internal or external glob.

This problem was added with v5.27.5 by replacing strchr with memchr,
allowing such illegal strings.
See L<[cperl #342]|https://github.com/perl11/cperl/issues/342>

=head2 Follow chroot with chdir("/")

Fixed two security issues with the chroot op:

* fail on embedded NUL in the chroot argument.
Set C<errno> to EINVAL.

* If a call to chroot is not followed by a call to chdir("/") the
chroot jail confinement can be violated.  In Perl_pp_chroot: A call to
chroot followed by an operation that may escape from the chroot jail.
Coverity CID #165302 Insecure chroot.

=head2 Set umask(0600) before calling mkstemp

POSIX 2008 demands such an umask, but it is still problematic on
Solaris, HP-UX and AIX and older libcs, e.g. glibc <= 2.06.
Temporarily set the umask such that the temp. file has 0600 permissions.

=head1 Incompatible Changes

=head2 Illegal NUL, syntax error

Embedded NUL bytes read from files, not used in filters, are not
whitespace anymore, they are syntax errors.

See L<[cperl #345]|https://github.com/perl11/cperl/issues/345> vs
L<[perl #105920]|https://rt.perl.org/Public/Bug/Display.html?id=105920>.

Parsing NUL bytes is now consistent from files with eval string.
C<\0> delimited C<q> quote is still valid though.

=head1 Deprecations

XXX Any deprecated features, syntax, modules etc. should be listed here.

=head2 No autovivification of hash slice anymore

This is a new syntax warning, which is deprecated, and will disappear
with v5.30c.  Hash slices and key/value hash slices autovivified in
subroutine arguments. This was a bug, but to check all your code for
correctness and portability we keep this warning for 2 releases.  See
L<[cperl #347]|https://github.com/perl11/cperl/issues/347> and
L<perldiag/"No autovivification of hash slice anymore">.

=head2 Module removals

XXX Remove this section if inapplicable.

The following modules will be removed from the core distribution in a
future release, and will at that time need to be installed from CPAN.
Distributions on CPAN which require these modules will need to list them as
prerequisites.

The core versions of these modules will now issue C<"deprecated">-category
warnings to alert you to this fact.  To silence these deprecation warnings,
install the modules in question from CPAN.

Note that these are (with rare exceptions) fine modules that you are encouraged
to continue to use.  Their disinclusion from core primarily hinges on their
necessity to bootstrapping a fully functional, CPAN-capable Perl installation,
not usually on concerns over their design.

=over

=item XXX

XXX Note that deprecated modules should be listed here even if they are listed
as an updated module in the L</Modules and Pragmata> section.

=back

[ List each other deprecation as a =head2 entry ]

=head1 Performance Enhancements

=over 4

=item *

All static method calls are now optimized to function calls at compile-time.

Before:

    $ cperl5.27.0d-nt -Dt -e'use strict'
    (-e:1)	nextstate
    (-e:1)	const(PV("strict.pm"))
    (-e:1)	require
    (-e:1)	nextstate
    (-e:1)	pushmark
    (-e:1)	const(PV("strict"))
    (-e:1)	method_named(->import)
    (-e:1)	entersub(strict::import)
    (-e:1)	enterxssub(strict::import)
    (-e:1)	leavesub

v5.27.1c:

    $ cperl5.27.1d-nt -Dt -e'use strict'
    (-e:1)	nextstate
    (-e:1)	const(PV("strict.pm"))
    (-e:1)	require
    (-e:1)	nextstate
    (-e:1)	pushmark
    (-e:1)	const(PV("strict"))
    (-e:1)	method_named(->import)
    (-e:1)	enterxssub(strict::import)
    (-e:1)	leavesub

v5.27.2c:

    $ cperl5.27.2d-nt -Dt -e'use strict'
    (-e:1)	nextstate
    (-e:1)	const(PV("strict.pm"))
    (-e:1)	require
    (-e:1)	nextstate
    (-e:1)	pushmark
    (-e:1)	const(PV("strict"))
    (-e:1)	gv(strict::import)
    (-e:1)	enterxssub(strict::import)
    (-e:1)	leavesub

See L<http://blogs.perl.org/users/rurban/2011/06/how-perl-calls-subs-and-methods.html>

We don't yet optimize typed scalars to a static call. We don't walk
the subtypes yet to find the method.

=item *

The three loop iterator ops are now a LOGOPs (in perl5 there is only
one, named C<iter>), they are combined with the previously subsequent
AND op to continue or end the loop. Thus inner loops are now smaller
and faster. 15%-50%.

e.g. before:

     f  <{> enteriter(next->q last->t redo->g) KS/DEF
     r  <0> iter_ary s
     s  <|> and(other->g) K/1
     g      <;> nextstate(main 559 (eval 15):1) v:{
     h      <$> gvsv(*_) s

Now:

     f  <{> enteriter(next->q last->s redo->g) KS/DEF
     r  <|> iter_ary(other->g) sK
     g      <;> nextstate(main 559 (eval 15):1) v:{
     h      <$> gvsv(*_) s

cperl-only, L<[cperl #138]|https://github.com/perl11/cperl/issues/138>.
Upstream 5.27 improved also a bit by skipping the AND op at run-time.
cperl removed it from the optree at compile-time.

=back

=head1 Modules and Pragmata

XXX All changes to installed files in F<cpan/>, F<dist/>, F<ext/> and F<lib/>
go here.  If Module::CoreList is updated, generate an initial draft of the
following sections using F<Porting/corelist-perldelta.pl>.  A paragraph summary
for important changes should then be added by hand.  In an ideal world,
dual-life modules would have a F<Changes> file that could be cribbed.

The list of new and updated modules is modified automatically as part of
preparing a Perl release, so the only reason to manually add entries here is if
you're summarising the important changes in the module update. (Also, if the
manually-added details don't match the automatically-generated ones, the
release manager will have to investigate the situation carefully.)

[ Within each section, list entries as an =item entry ]

=head2 New Modules and Pragmata

=over 4

=item *

XXX

=back

=head2 Updated Modules and Pragmata

=over 4

=item L<Attribute::Handlers> 1.00_01

fix autovivification bug with hash slice args to a function.

=item L<Compress::Raw::Zlib>

fix upstream deflate.
See L<https://github.com/madler/zlib/pull/327>

=item L<Cpanel::JSON::XS> 3.0240

Simplify C<allow_singlequote> check, coverity cid #165321.
Remove logical dead code.

=item L<Data::Dumper>  2.167_03

XS improvements

=item L<Devel::PPPort> 3.36_04

mkppport called PPPort_pm.PL without
passing through MAKEFLAGS. Add --quiet support there

=item L<ExtUtils::Miniperl> 1.08

Support B<afl-fuzz> with L<afl-clang-fast|perlhacktips/"afl-fuzz">

=item L<ExtUtils::ParseXS> 3.36_03

skip C<PUTBACK;return;> on XSRETURN in PPCODE

remove perl5 incompatible C<__attribute__global__> needed for -flto.
C<XS_EXTERNAL> has it already.

=item L<I18N::LangTags>  0.42_01

Linkify docs.

=item L<IO>  1.38_01

run-time load Carp

=item L<IO::Socket::IP> 0.39_02

Fix new Autovivified hash slice warning

=item L<JSON::PP> 2.97001_04

Merged 2.97001 from cpan with ours.

=item L<Hash::Util>  0.22_01

XS formatting

=item L<HTTP::Tiny>  0.070_01

Fix new Autovivified hash slice warning

=item L<List::Util> 1.49_10

Fixup the new pairmap spill code.

=item L<Module::CoreList> 5.20180101c

=item L<Module::Load::Conditional> 0.68_02

Suppress new Autovivified hash slice warning

=item L<mro> 1.21_01

formatting, cperl enhancements

=item L<OS2::Process>  1.12_01

=item L<PerlIO::scalar> 0.29_01

only comment

=item L<PerlIO::via> 0.17_01

Protect from NULL arg.

=item L<Pod::Checker> 1.73_01

no strict hashpairs

=item L<Term::ReadKey> 2.37_03

Protect from fileno returning -1, invalid file arg.
Reformatted.

=item L<Tie::Hash::NamedCapture> 0.10_01

use croak_no_modify_sv()

=item L<Unicode::Collate> 1.25_01

Skip redefinition warnings on cperl since 5.27.2

=item L<Unicode::UCD>  0.68_01

=item L<Win32>  0.52_01

=back

=head2 Removed Modules and Pragmata

=over 4

=item L<Locale::Codes> 3.55

Deprecated with v5.27.2c

=back

=head1 Documentation

XXX Changes to files in F<pod/> go here.  Consider grouping entries by
file and be sure to link to the appropriate page, e.g. L<perlfunc>.

=head2 New Documentation

XXX Changes which create B<new> files in F<pod/> go here.

=head3 L<XXX>

XXX Description of the purpose of the new file here

=head2 Changes to Existing Documentation

We have attempted to update the documentation to reflect the changes
listed in this document.  If you find any we have missed, send email
to L<perlbug@perl.org|mailto:perlbug@perl.org>.

XXX Changes which significantly change existing files in F<pod/> go here.
However, any changes to F<pod/perldiag.pod> should go in the L</Diagnostics>
section.

Additionally, the following selected changes have been made:

=head3 L<XXX>

=over 4

=item *

XXX Description of the change here

=back

=head1 Diagnostics

The following additions or changes have been made to diagnostic output,
including warnings and fatal error messages.  For the complete list of
diagnostic messages, see L<perldiag>.

XXX New or changed warnings emitted by the core's C<C> code go here.  Also
include any changes in L<perldiag> that reconcile it to the C<C> code.

=head2 New Diagnostics

XXX Newly added diagnostic messages go under here, separated into New Errors
and New Warnings

=head3 New Errors

=over 4

=item *

XXX L<message|perldiag/"message">

=back

=head3 New Warnings

=over 4

=item *

XXX L<message|perldiag/"message">

=back

=head2 Changes to Existing Diagnostics

XXX Changes (i.e. rewording) of diagnostic messages go here

=over 4

=item *

XXX Describe change here

=back

=head1 Utility Changes

XXX Changes to installed programs such as F<perlbug> and F<xsubpp> go here.
Most of these are built within the directory F<utils>.

[ List utility changes as a =head2 entry for each utility and =item
entries for each change
Use L<XXX> with program names to get proper documentation linking. ]

=head2 L<XXX>

=over 4

=item *

XXX

=back

=head1 Configuration and Compilation

XXX Changes to F<Configure>, F<installperl>, F<installman>, and analogous tools
go here.  Any other changes to the Perl build process should be listed here.
However, any platform-specific changes should be listed in the
L</Platform Support> section, instead.

[ List changes as an =item entry ].

=over 4

=item *

XXX

=back

=head1 Testing

XXX Any significant changes to the testing of a freshly built perl should be
listed here.  Changes which create B<new> files in F<t/> go here as do any
large changes to the testing harness (e.g. when parallel testing was added).
Changes to existing files in F<t/> aren't worth summarizing, although the bugs
that they represent may be covered elsewhere.

XXX If there were no significant test changes, say this:

Tests were added and changed to reflect the other additions and changes
in this release.

XXX If instead there were significant changes, say this:

Tests were added and changed to reflect the other additions and
changes in this release.  Furthermore, these significant changes were
made:

[ List each test improvement as an =item entry ]

=over 4

=item *

C<make minitest> can now be successfully be run directly after C<make miniperl>.
The unicode datafiles are now built before, and tests pass even if no module
was built or mktables failed.

=back

=head1 Platform Support

XXX Any changes to platform support should be listed in the sections below.

[ Within the sections, list each platform as an =item entry with specific
changes as paragraphs below it. ]

=head2 New Platforms

XXX List any platforms that this version of perl compiles on, that previous
versions did not.  These will either be enabled by new files in the F<hints/>
directories, or new subdirectories and F<README> files at the top level of the
source tree.

=over 4

=item XXX-some-platform

XXX

=back

=head2 Discontinued Platforms

XXX List any platforms that this version of perl no longer compiles on.

=over 4

=item XXX-some-platform

XXX

=back

=head2 Platform-Specific Notes

XXX List any changes for specific platforms.  This could include configuration
and compilation changes or changes in portability/compatibility.  However,
changes within modules for platforms should generally be listed in the
L</Modules and Pragmata> section.

=over 4

=item XXX-some-platform

XXX

=back

=head1 Internal Changes

=over 4

=item *

With a threaded perl, GV's are relocated as READONLY PADs.
Add an abstraction L<perlintern/op_gv_set> to simplify that.

=item *

Removed the obsolete C<OA_PADOP> class. Invalid and unused since 5.6.0.
Kept C<OP_IS_PADOP> and made it legal for threaded perls.
The L<B> modules still print PADOP C<'#'> ops as such, which were dynamically
converted from SVOP's to PADOP's threaded.

=back

=head1 Selected Bug Fixes

=over 4

=item *

Fixed error message for illegal charnames, and avoid passing NUL into
the charnames lookup, which is a potential security threat.  E.g. on
"\N{TILDE\000}" report "Missing right brace on \\N\{\}" as before
with 5.27.2 and on "\N{TILDE\001}" report "Unknown charname 'TILDE\1'" and
not "Unknown charname 'TILDE'".  perl5.27.5 started reporting those
errors with "Unknown charname 'TILDE'" hiding all characters behind
the embedded NUL or any non-printable character.
L<[cperl #342]|https://github.com/perl11/cperl/issues/342>

=item *

Fixed endless loop in the parser with a syntax error on an aborted
class declaration, such as e.g. with C<class $>. The previous behavior
was repeating the warning message C<Bareword found where operator expected>
endlessly.
L<[cperl #346]|https://github.com/perl11/cperl/issues/346>

=item *

Fixed autovivifaction of hash slices and key/value hash slices in sub args.
They are now consistent with a list of hash elements.
hash slices still autovivify in for loops.

There's also a new syntax warning about this change,
L<perldiag/"No autovivification of hash slice anymore">
L<[cperl #347]|https://github.com/perl11/cperl/issues/347>.

=item *

Fixed wrong C<panic: distributed hash flood> when dealing with
large C<%^H> hints hashes, with >127 entries, such as C<_charnames.pm> in
C<Regexp::Common>. Fixed the logic dealing with such a hints hash.
L<[cperl #350]|https://github.com/perl11/cperl/issues/350>.

=item *

Fixed endless rpeep compiler loop with a constant loop and a nested loop,
which e.g. broke C<Net:HTTP>.
L<[cperl #349]|https://github.com/perl11/cperl/issues/349>.

=back

=head1 Known Problems

XXX Descriptions of platform agnostic bugs we know we can't fix go here.  Any
tests that had to be C<TODO>ed for the release would be noted here.  Unfixed
platform specific bugs also go here.

[ List each fix as an =item entry ]

=over 4

=item *

XXX

=item *

Fixed return type of C<DynaLoader::dl_find_symbol_anywhere()>,
the address, not the name.
L<[cperl #352]|https://github.com/perl11/cperl/issues/352>.

=back

=head1 Errata From Previous Releases

=over 4

=item *

XXX Add anything here that we forgot to add, or were mistaken about, in
the perldelta of a previous release.

=back

=head1 Obituary

XXX If any significant core contributor has died, we've added a short obituary
here.

=head1 Acknowledgements

XXX Generate this with:

    cperl Porting/acknowledgements.pl cperl-5.27.2..HEAD -c

=head1 Reporting Bugs

If you find what you think is a bug, you might check the perl bug database
at L<https://rt.perl.org/> .  There may also be information at
L<http://www.perl.org/> , the Perl Home Page.

If you believe you have an unreported bug, please run the L<cperlbug> program
included with your release.  Be sure to trim your bug down to a tiny but
sufficient test case.  Your bug report, along with the output of C<perl -V>,
will be sent off to perlbug@perl.org to be analysed by the Perl porting team.

If you think it's a cperl specific bug or trust the cperl developers more 
please file an issue at L<https://github.com/perl11/cperl/issues>.

If the bug you are reporting has security implications which make it
inappropriate to send to a publicly archived mailing list, then see
L<perlsec/SECURITY VULNERABILITY CONTACT INFORMATION>
For details of how to report the issue.

=head1 SEE ALSO

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

The F<INSTALL> file for how to build Perl.

The F<README> file for general stuff.

The F<Artistic> and F<Copying> files for copyright information.

=cut
