#!/bin/sh

test -f Porting/perl_version || exit 1
ver=$(Porting/perl_version)

mkdir ../cperl-${ver}-build 2>/dev/null \
    || rm -rf ../cperl-${ver}-build ../cperl-${ver}
cp -frp .git ../cperl-${ver}-build/
cd ../cperl-${ver}-build
git reset --hard
git clean -dxf
#cp ../cperl/Porting/makerel Porting/
perl Porting/makerel -x

gpg -a -b cperl-${ver}.tar.gz
gpg -a -b cperl-${ver}.tar.xz
sha256sum cperl-${ver}.tar.*
