################################################################################
#
#            !!!!!   Do NOT edit this file directly!   !!!!!
#
#            Edit mktests.PL and/or parts/inc/HvNAME instead.
#
#  This file was automatically generated from the definition files in the
#  parts/inc/ subdirectory by mktests.PL. To learn more about how all this
#  works, please read the F<HACKERS> file that came with this distribution.
#
################################################################################

BEGIN {
  if ($ENV{'PERL_CORE'}) {
    chdir 't' if -d 't';
    @INC = ('../lib', '../ext/Devel-PPPort/t') if -d '../lib' && -d '../ext';
    require Config; import Config;
    use vars '%Config';
    if (" $Config{'extensions'} " !~ m[ Devel/PPPort ]) {
      print "1..0 # Skip -- Perl configured without Devel::PPPort module\n";
      exit 0;
    }
  }
  else {
    unshift @INC, 't';
  }

  sub load {
    eval "use Test";
    require 'testutil.pl' if $@;
  }

  if (11) {
    load();
    plan(tests => 11);
  }
}

use Devel::PPPort;
use strict;
$^W = 1;

package Devel::PPPort;
use vars '@ISA';
require DynaLoader;
@ISA = qw(DynaLoader);
bootstrap Devel::PPPort;

package main;

ok(Devel::PPPort::HvNAME_get(\%Devel::PPPort::), 'Devel::PPPort');
ok(Devel::PPPort::HvNAME_get({}), undef);

ok(Devel::PPPort::HvNAMELEN_get(\%Devel::PPPort::), length('Devel::PPPort'));
ok(Devel::PPPort::HvNAMELEN_get({}), 0);

ok(Devel::PPPort::HvNAMELEN({}), 0);
ok(Devel::PPPort::HvENAME({}), undef);
ok(Devel::PPPort::HvENAMELEN({}), 0);
ok(Devel::PPPort::HvENAMEUTF8({}), 0);

ok(Devel::PPPort::HvNAMEUTF8(\%Devel::PPPort::), 0);

if ($] > 5.015006) {
   use utf8;
   ok(Devel::PPPort::HvNAMEUTF8(\%αaαb::), 1);
   ok(Devel::PPPort::HvENAMEUTF8(\%αaαb::), 1);
} else {
  ok(1, 1, "skip HvNAMEUTF8 with $]");
  ok(1, 1, "skip HvENAMEUTF8 with $]");
}

