#!/bin/sh
# git reset --hard all cperl branches (reset rebased changes from remote)

echo -n "Really reset hard all bugfix/|feature branches to remote cp? You will loose all your local changes (Ctrl-C) "
read y
git checkout master
git pull --rebase || exit

for b in `git branch | egrep 'bugfix/|feature/'`; do
    git checkout $b && git reset --hard cp/$b
done
