---
abstract: The cperl language interpreter
author:
  - rurban@cpanel.net
build_requires: {}
dynamic_config: 1
generated_by: CPAN::Meta version 2.150010, CPAN::Meta::Converter version 2.150010
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cperl
no_index:
  directory:
    - cpan
    - dist/Attribute-Handlers
    - dist/autouse
    - dist/base
    - dist/bignum
    - dist/Carp
    - dist/constant
    - dist/Data-Dumper
    - dist/Devel-SelfStubber
    - dist/Dumpvalue
    - dist/Env
    - dist/Exporter
    - dist/ExtUtils-CBuilder
    - dist/ExtUtils-Constant
    - dist/ExtUtils-ParseXS
    - dist/Filter-Simple
    - dist/I18N-Collate
    - dist/if
    - dist/IO/
    - dist/lib/
    - dist/Locale-Maketext
    - dist/Math-BigInt
    - dist/Math-BigInt-FastCalc
    - dist/Math-BigRat
    - dist/Module-CoreList
    - dist/Net-Ping
    - dist/PathTools
    - dist/Safe
    - dist/Search-Dict
    - dist/SelfLoader
    - dist/Storable
    - dist/Term-Complete
    - dist/Term-ReadLine
    - dist/Text-Abbrev
    - dist/Thread-Queue
    - dist/Thread-Semaphore
    - dist/threads
    - dist/threads-shared
    - dist/Tie-File
    - lib/perl5db
    - win32
  file:
    - autodoc.pl
    - dist/IO/ChangeLog
    - dist/IO/hints/sco.pl
    - dist/IO/IO.pm
    - dist/IO/IO.xs
    - dist/IO/lib/IO/Dir.pm
    - dist/IO/lib/IO/File.pm
    - dist/IO/lib/IO/Handle.pm
    - dist/IO/lib/IO/Pipe.pm
    - dist/IO/lib/IO/Poll.pm
    - dist/IO/lib/IO/Seekable.pm
    - dist/IO/lib/IO/Select.pm
    - dist/IO/lib/IO/Socket.pm
    - dist/IO/lib/IO/Socket/INET.pm
    - dist/IO/lib/IO/Socket/UNIX.pm
    - dist/IO/Makefile.PL
    - dist/IO/poll.c
    - dist/IO/poll.h
    - dist/IO/README
    - dist/IO/t/cachepropagate-tcp.t
    - dist/IO/t/cachepropagate-udp.t
    - dist/IO/t/cachepropagate-unix.t
    - dist/IO/t/IO.t
    - dist/IO/t/io_const.t
    - dist/IO/t/io_dir.t
    - dist/IO/t/io_dup.t
    - dist/IO/t/io_file.t
    - dist/IO/t/io_file_export.t
    - dist/IO/t/io_leak.t
    - dist/IO/t/io_linenum.t
    - dist/IO/t/io_multihomed.t
    - dist/IO/t/io_pipe.t
    - dist/IO/t/io_poll.t
    - dist/IO/t/io_sel.t
    - dist/IO/t/io_sock.t
    - dist/IO/t/io_taint.t
    - dist/IO/t/io_tell.t
    - dist/IO/t/io_udp.t
    - dist/IO/t/io_unix.t
    - dist/IO/t/io_utf8.t
    - dist/IO/t/io_utf8argv.t
    - dist/IO/t/io_xs.t
    - dist/lib/lib_pm.PL
    - dist/lib/Makefile.PL
    - dist/lib/t/01lib.t
    - ext/Config/Config.pm
    - ext/Config/Config_xs.in
    - ext/Config/Config_xs.out
    - ext/Config/Config_xs.PL
    - ext/Config/Dummy.c
    - ext/Config/gperftest.in
    - ext/Config/Makefile.PL
    - ext/Config/t/Config.t
    - ext/Config/t/XSConfig.t
    - ext/Config/typemap
    - lib/unicore/mktables
    - pod/perlfilter.pod
    - pod/perlpodstyle.pod
    - Porting/Maintainers.pm
    - Porting/perldelta_template.pod
    - TestInit.pm
    - vutil.c
    - vutil.h
    - vxs.inc
resources:
  bugtracker: http://github.com/perl11/cperl/issues
  homepage: http://perl11.org/cperl/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/perl11/cperl/
version: '5.022005'
x_serialization_backend: YAML::XS version 0.75
