# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,# If the AutoSplit module has been loaded before we got initialized
0,0,0,# (specifically before we redirected the opcodes used when compiling)
0,0,0,# then the profiler won't profile AutoSplit code so the test will fail
0,0,0,# because the results won't match.
0,0,0,# The tricky part is that we need to take care to avoid being tripped up
0,0,0,# by the fact that XSLoader will fallback to using DynaLoader in some cases
0,0,0,# and DynaLoader uses AutoSplit.
0,0,0,# See Makefile.PL for how we avoid XSLoader fallback to using DynaLoader.
0,0,0,
0,0,0,BEGIN {
0,0,0,use AutoSplit;
0,0,0,mkdir('./auto');
0,0,0,autosplit('test14', './auto', 1, 0, 0);
0,0,0,}
0,0,0,
0,0,0,use test14;
0,1,0,test14::pre();
0,1,0,test14::foo();
0,1,0,test14::bar();
