# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,sub foo {
0,2,0,eval "shift;
0,0,0,shift;
0,0,0,bar();";
0,0,0,}
0,0,0,
0,0,0,sub bar {
0,3,0,eval '$a = 10_001; while (--$a) { ++$b }';
0,0,0,}
0,0,0,
0,1,0,foo();
0,1,0,foo();
0,1,0,bar();
