# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
~1,1,0,$code = eval "sub { sleep 1; }$Devel::NYTProf::StrEvalTestPad";
0,1,0,$code->();
