# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,# tests given/when.  Can only be tested by Perl 5.10 or later.
0,0,0,
0,0,0,use warnings;
0,0,0,use strict;
0,0,0,
0,0,0,use feature ":5.10";
0,0,0,
0,0,0,sub foo {
0,2,0,my $whameth = shift;
0,2,0,given ($whameth) {
0,2,0,when(/\d/) {
0,0,0,say "number-like";
0,0,0,}
0,1,0,when(/\w/) {
0,0,0,say "word-like";
0,0,0,}
0,0,0,}
0,0,0,}
0,0,0,
0,0,0,sub bar {
0,2,0,my $zlott = shift;
0,2,0,if($zlott =~ /\d/) {
0,0,0,print "number-like\n";
0,0,0,} elsif($zlott =~ /\w/) {
0,0,0,print "word-like\n";
0,0,0,} 
0,0,0,}
0,0,0,
0,0,0,
0,1,0,foo("baz");
0,1,0,foo(17);
0,1,0,bar("baz");
0,1,0,bar(17);
