# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,use vars qw/$b/;
0,0,0,BEGIN {
0,0,0,$b = eval "sub {1}";
0,0,0,}
0,1,0,&$b;
0,1,0,&$b;
