# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,1,0,shift;
0,1,0,DB::disable_profile();
0,0,0,shift;
0,1,0,DB::enable_profile();
0,1,0,shift;
0,0,0,DB::disable_profile();
0,0,0,shift; # finish with profile disabled
