# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,# Testing various types of eval calls. Some are processed differently internally
0,0,0,
0,0,0,sub foo {
0,3,0,print "in sub foo\n";
0,0,0,}
0,0,0,
0,0,0,sub bar {
0,1,0,print "in sub bar\n";
0,0,0,}
0,0,0,
0,0,0,sub baz {
0,1,0,print "in sub baz\n";
0,2,0,eval { foo();    # two stmts executed on this line (eval + foo() call)
0,1,0,foo(); }; # one stmt  executed on this line
0,2,0,eval { x();      # two stmts executed on this line (eval + x() call), fails out of eval
0,0,0,x(); };   # zero stmts because previous statement threw an exception
0,0,0,}
0,0,0,
0,1,0,eval "foo();";     # one stmt in this fid, one statement in eval fid
0,2,0,eval { bar(); };   # two stmts
0,1,0,baz();
