# Profile data generated by Devel::NYTProf::Reader
# More information at http://metacpan.org/release/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,# test nested string evals
0,0,0,
0,0,0,
0,3,0,sub foo { 1 }
0,1,0,my $code = q{
0,0,0,select(undef,undef,undef,0.2);
0,0,0,foo();
0,0,0,eval q{
0,0,0,select(undef,undef,undef,0.2);
0,0,0,foo();
0,0,0,eval q{
0,0,0,select(undef,undef,undef,0.2);
0,0,0,foo();
0,0,0,}
0,0,0,}
0,0,0,};
0,1,0,eval $code;
